### PR TITLE
Feat : Added Product Page

### PR DESCRIPTION
**Pull request by SaurabhChawda**
Screenshot (222)
I have an added product page in Trendy-T. It contains different features.
1. Search Product.
2. Filter by price, category, rating, and sorting.
3. Products 
4. Header
5. Footer

### CODE REVIEW

**Review by mariyasada — APPROVED** [review]
code looks good

**Comment by SaurabhChawda** [comment]
> code looks good

ThankYou

**Comment by Namrata-J** [comment]
Looks good, and also it's responsive, which is good thing!!

**Review by Namrata-J — APPROVED** [review]

**Comment by SaurabhChawda** [comment]
> Looks good, and also it's responsive, which is a good thing!!

ThankYou

**Pull request merged**
