### PR TITLE
Feat: Added Login signup page

### PR DESCRIPTION
**Pull request by SaurabhChawda**
Signup
Login
I have Added a login and sign-up page in Trendy-T. Users can log in and open a new account using these pages.

### CODE REVIEW

**Review by ajit-sharmaGH — APPROVED** [review]
Everything is fine, css naming  are super

**Review by deepak29-git — APPROVED** [review]
Everything looks good and responsiveness are also good

**Comment by SaurabhChawda** [comment]
> Everything is fine, css naming are super

ThankYou Ajit

**Comment by SaurabhChawda** [comment]
> Everything looks good and responsiveness are also good

ThankYou Deepak.

**Pull request merged**
